FROM php:8.2.0beta3-fpm-buster
# COPY ./run.sh /opt/run.sh
# COPY ./sources.list /etc/apt/sources.list
LABEL Author="Okami-Chen"
LABEL Version="php-8.1"
LABEL Description="PHP 8.1"
ARG timezone

ENV TIMEZONE=${timezone:-"Asia/Shanghai"} \
    APP_ENV=production \
    LANG=C.UTF-8

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions \
&& apt-get update -y --fix-missing && apt-get upgrade -y && apt-get -y install --no-install-recommends wget libssl-dev libcurl4-openssl-dev \
&& install-php-extensions intl ldap dba shmop calendar exif gettext pcntl sysvsem sysvshm \
pdo_mysql mysqli bcmath gd soap sockets zip bz2 redis \
&& cp /usr/bin/clear /usr/bin/cls && cd /tmp \
# && wget https://github.com/swoole/swoole-src/archive/master.tar.gz \
# && tar zxvf master.tar.gz \
# && mv swoole-src* swoole-src && cd swoole-src \
# && phpize && ./configure --enable-openssl --enable-sockets --enable-mysqlnd \
# && make && make install \
# && docker-php-ext-enable swoole \
&& php -r "copy('https://install.phpcomposer.com/installer', 'composer-setup.php');" \
&& php composer-setup.php \
&& php -r "unlink('composer-setup.php');" \
&& mv composer.phar /usr/local/bin/composer \
&& chmod a+x /usr/local/bin/composer \
&& composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/ \
&& rm -rf /var/cache/apk/* /tmp/* /usr/share/man /var/lib/apt/lists/* \
&& apt-get clean
